name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

   # - name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1

 #   - name: Setup MSBuild.exe
#      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Install dependencies
      run: dotnet restore "${{ github.workspace }}/GameAppBV/GameAppBV.sln"
  
    
  
    - name: Build DotNET35
      run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\GameAppBV\GameAppBV.sln --configuration Release --no-restore


  #  - name: Build
    #  run: dotnet build "${{ github.workspace }}/GameAppBV/GameAppBV.sln" --configuration Release --no-restore
    
    - name: Test
      run: |
        dotnet test "${{ github.workspace }}/GameAppBV/GameAppBV.sln" --no-restore --verbosity normal 
      
    - name: Publish
      run: |
        dotnet publish "${{ github.workspace }}/GameAppBV/GameAppBV/GameAppBV.csproj" -c Release -o GameAppBV
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: GameAppBVbuildartifacts
        # A file, directory or wildcard pattern that describes what to upload
        path: GameAppBV/**
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 90
